"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fs_monkey_1 = require("fs-monkey");
const memfs_1 = require("memfs");
const unionfs_1 = require("unionfs");
const fs = require("fs");
exports.vol = new memfs_1.Volume();
const fs2 = Object.assign({}, fs);
unionfs_1.ufs.use(fs2).use(exports.vol);
fs_monkey_1.patchFs(unionfs_1.ufs);
